### ISSUE TITLE
v4+ places imports inside parser function, but types using those imports outside

### ISSUE THREAD

**Issue by ConradHughes** [metadevpro/ts-pegjs#134]
When I upgrade from 3.1.0 to any 4.x version, the imports I have in `{{` global initialization `}}` are placed _inside_ the `const peggyParser` definition.  This breaks compilation because type definitions at the end of the generated source file — which need these imports — can't then find imported types.  I see no mention of this breaking change in the v4 release notes.  Any suggestions please?

As a side note, if I have v4 `peggy` _and_ v4 `ts-pegjs` I also get complaints about `Cannot find module ts-pegjs/node_modules/prettier/standalone imported from tspegjs.mjs`.  I assume this is an ESM issue; any workaround for folk stuck (for the time being) on CJS?

**Comment by pickaxe828** [comment]
Can replicate this issue, and the non-top-level `import` has also been troublesome for me as well
